Repository Merge-co/OIL-JANG_FE, pull requests merged in 2023-11, with the labels that each got.

#50 [FE][FEATURE] 상품 카테고리 출력 작업 중
  src/App.js
  src/apis/ProductAPICalls.js
  src/apis/dummy
  src/components/common/Header.js
  src/components/product/MergeBox.module.css
  src/components/product/MergeMain.module.css
  src/components/product/ProductCategory.js
  src/components/product/ProductCategory.module.css
  src/components/product/ProductCategoryModule.js
  src/components/product/ProductDetailCss.module.css
  src/components/product/ProductItem.module.css
  src/components/product/ProductList.module.css
  src/components/product/ProductMoneyFilter.module.css
  src/components/product/WishList.module.css
  src/components/product/dummy
  src/pages/product/Merge.js
Labels: FETURE🎉

#52 20231113-product-003 카테고리 작업 중
  src/components/product/ProductCategory.js
  src/styles/MergeBox.module.css
  src/styles/MergeMain.module.css
  src/styles/ProductCategory.module.css
  src/styles/ProductDetailCss.module.css
  src/styles/ProductItem.module.css
  src/styles/ProductList.module.css
  src/styles/ProductMoneyFilter.module.css
  src/styles/WishList.module.css
  src/styles/dummy
Labels: FEATURE🎉

#54 :technologist: [FE][FEATURE] 신고관리 조회
  package-lock.json
  package.json
  src/App.js
  src/admin/Management.js
  src/apis/ReportAPICalls.js
  src/components/common/AdminHeader.js
  src/components/common/Header.js
  src/layouts/Layout.js
  src/modules/ReportModule.js
  src/modules/index.js
  src/pages/report/Report.js
  src/styles/Admin.css
Labels: FEATURE🎉

#53 [FE][FEATURE] 꾸러미 스타일 입히는 중입니다.
  src/App.js
  src/components/common/Header.js
  src/components/product/MergeBox.js
  src/components/product/MergeCategory.js
  src/components/product/ProductCategory.js
  src/components/product/ProductFilter.js
  src/components/product/ProductItem.js
  src/components/product/ProductList.js
  src/pages/product/Merge.js
  src/styles/Button.module.css
  src/styles/product/MergeBox.module.css
  src/styles/product/MergeCategory.module.css
  src/styles/product/MergeLayout.module.css
  src/styles/product/MergeMain.module.css
  src/styles/product/ProductCategory.module.css
  src/styles/product/ProductDetailCss.module.css
  src/styles/product/ProductFilter.module.css
  src/styles/product/ProductItem.module.css
  src/styles/product/ProductList.module.css
  src/styles/product/ProductMoneyFilter.module.css
  src/styles/product/WishList.module.css
Labels: FEATURE🎉

#55 [FE][FEATURE] 꾸러미 기능 추가 중입니다.
  public/images/categoryArrow.svg
  public/images/dummy
  public/images/home.svg
  public/images/mergeCancelBtn.svg
  public/images/reportBtn.svg
  public/images/reset.svg
  public/index.html
  src/App.css
  src/apis/ProductAPICalls.js
  src/components/common/PagingBar.js
  src/components/product/MergeBox.js
  src/components/product/ProductCategory.js
  src/components/product/ProductItem.js
  src/components/product/ProductList.js
  src/modules/ProductCategoryModule.js
  src/modules/ProductModule.js
  src/modules/index.js
  src/pages/product/Merge.js
  src/styles/PagingBar.module.css
  src/styles/product/MergeBox.module.css
  src/styles/product/ProductItem.module.css
  src/styles/product/ProductList.module.css
Labels: FEATURE🎉

#58 [FE][FEATURE]
  src/apis/ProductAPICalls.js
  src/components/common/PagingBar.js
  src/components/product/MergeBox.js
  src/components/product/MergeCategory.js
  src/components/product/ProductCategory.js
  src/components/product/ProductFilter.js
  src/components/product/ProductItem.js
  src/components/product/ProductList.js
  src/modules/MergeModule.js
  src/modules/PagingModule.js
  src/modules/ProductListModule.js
  src/modules/ProductModule.js
  src/modules/index.js
  src/pages/product/Merge.js
  src/styles/PagingBar.module.css
  src/styles/product/MergeBox.module.css
  src/styles/product/MergeCategory.module.css
  src/styles/product/MergeLayout.module.css
  src/styles/product/ProductList.module.css
Labels: FEATURE🎉

#59 [FE][Feature] 로그인 기능 추가
  .env
  package-lock.json
  package.json
  src/App.js
  src/apis/UserAPICalls.js
  src/components/common/Header.js
  src/modules/UserModule.js
  src/pages/user/Login.js
  src/pages/user/Test.js
  src/pages/user/dummy
  src/utils/TokenUtils.js
Labels: FEATURE🎉

#66 [FE][FEATURE] 상품 상세 이미지 슬라이드
  package-lock.json
  package.json
  src/App.js
  src/apis/ProductAPICalls.js
  src/apis/WishListAPICalls.js
  src/components/common/Footer.js
  src/components/common/Header.js
  src/components/common/SubHeader.js
  src/components/product/MergeBox.js
  src/components/product/MergeItemBox.js
  src/components/product/MoneyFilter.js
  src/components/product/ProductCategory.js
  src/components/product/ProductItem.js
  src/components/product/ProductList.js
  src/layouts/SubHeaderLayout.js
  src/modules/CookieModule.js
  src/modules/ProductModule.js
  src/modules/WishListModule.js
  src/modules/index.js
  src/pages/product/Merge.js
  src/pages/product/UsedProduct.js
  src/pages/product/UsedProductDetail.js
  src/pages/product/UserProductDetailImg.js
  src/pages/wish/WishList.js
  src/pages/wish/dummy
  src/styles/Button.module.css
  src/styles/Footer.module.css
  src/styles/SubHeader.module.css
  src/styles/product/MergeBox.module.css
  src/styles/product/MergeLayout.module.css
  src/styles/product/ProductDetailCss.module.css
  src/styles/product/ProductFilter.module.css
  src/styles/product/ProductItem.module.css
  src/styles/product/ProductList.module.css
  src/styles/product/ProductMoneyFilter.module.css
  src/styles/wishList/WishList.module.css
Labels: FEATURE🎉

#65 [FE][FEATURE]쪽지 리스트 조회
  package-lock.json
  src/App.js
  src/apis/MessageAPICalls.js
  src/components/common/AdminHeader.js
  src/components/common/Header.js
  src/modules/CookieModule.js
  src/modules/MessageModule.js
  src/pages/message/MessageList.js
Labels: FEATURE🎉

#69 [FE][FEATURE] 상품등록 완료
  src/apis/SellingAPICalls.js
  src/apis/SellingAPUCalls.js
  src/modules/CookieModule.js
  src/modules/SellingProductModule.js
  src/pages/product/AddProduct.js
Labels: FEATURE🎉

#68 :memo:[FE][FEATURE]신고Search기능 추가
  src/App.js
  src/apis/ReportAPICalls.js
  src/components/common/AdminNav.js
  src/components/common/Nav.js
  src/modules/ReportModule.js
  src/pages/product/Main.js
  src/pages/report/ProcessDetail.js
  src/pages/report/Report.js
  src/pages/report/ReportManagement.js
  src/pages/report/ReportSearch.js
  src/pages/report/ReportUpdate.js
  src/pages/report/Search.js
Labels: FEATURE🎉

#70 [FE][FEATURE] 쪽지 등록 기능
  src/App.js
  src/apis/MessageAPICalls.js
  src/components/common/Header.js
  src/components/common/PagingBar.js
  src/components/message/Message.js
  src/components/message/MessageMenu.js
  src/components/message/Modal.js
  src/components/message/SearchForm.js
  src/pages/message/MessagModal.js
  src/pages/message/MessageDetail.js
  src/pages/message/MessageList.js
  src/styles/PagingBar.module.css
  src/styles/message/MessageDetail.module.css
  src/styles/message/MessageList.module.css
  src/styles/message/Modal.module.css
Labels: FEATURE🎉, BUG🐛

#71 [FE] [FEATURE] 내 판매목록 진행중
  package-lock.json
  package.json
  src/App.js
  src/apis/MyProductAPICalls.js
  src/components/common/SubHeader.js
  src/modules/SellingListModule.js
  src/pages/product/MyProductList.js
Labels: FEATURE🎉

#73 [FE][FEATURE] 쪽지 등록 완성
  .idea/.gitignore
  .idea/FE-oiljang-1123-01.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/apis/MessageAPICalls.js
  src/components/common/Footer.js
  src/pages/message/MessageDetail.js
  src/pages/message/MessageList.js
  src/styles/Footer.module.css
  src/styles/message/MessageList.module.css
Labels: FEATURE🎉, BUG🐛

#77 :ambulance: [BE][FEATURE]신고기능 Search 구현(완)
  src/App.js
  src/apis/ReportAPICalls.js
  src/components/common/AdminNav.js
  src/components/common/Header.js
  src/modules/CookieModule.js
  src/modules/ProcessModule.js
  src/modules/ReportModule.js
  src/modules/index.js
  src/pages/product/UsedProductDetail.js
  src/pages/report/ProcessDetail.js
  src/pages/report/ProcessManagement.js
  src/pages/report/Report.js
  src/pages/report/ReportSearch.js
  src/pages/report/ReportUpdate.js
  src/pages/report/Search.js
  src/styles/Header.module.css
  src/styles/message/MessageDetail.module.css
  src/styles/report/ReportCSS.module.css
Labels: FEATURE🎉, BUG🐛

#76 [FE][FEATURE] 메인 페이지 작성
  public/images/product/original/dummy.txt
  public/images/product/thumbnail/dummy.txt
  public/images/siteImage/bannerImg1.png
  public/images/siteImage/categoryArrow.svg
  public/images/siteImage/home.svg
  public/images/siteImage/logInIcon.png
  public/images/siteImage/logInIcon.svg
  public/images/siteImage/logOutIcon.png
  public/images/siteImage/logOutIcon.svg
  public/images/siteImage/logo.svg
  public/images/siteImage/mergeCancelBtn.svg
  public/images/siteImage/messageIcon.svg
  public/images/siteImage/messageReceived.svg
  public/images/siteImage/reportBtn.svg
  public/images/siteImage/reset.svg
  public/images/siteImage/sample.jpg
  public/images/siteImage/userIcon.png
  public/images/siteImage/userIcon.svg
  public/images/siteImage/weeklyHot.png
  public/images/siteImage/weeklyHot.svg
  public/images/userProfile/original/dummy.txt
  public/images/userProfile/thumbnail/dummy.txt
  src/apis/ProductAPICalls.js
  src/apis/WishListAPICalls.js
  src/components/common/Header.js
  src/components/common/PagingBar.js
  src/components/product/MergeBox.js
  src/components/product/MergeItemBox.js
  src/components/product/MoneyFilter.js
  src/components/product/ProductCategory.js
  src/components/product/ProductItem.js
  src/components/product/ProductList.js
  src/pages/product/Main.js
  src/pages/product/Merge.js
  src/pages/product/UsedProduct.js
  src/pages/product/UsedProductDetail.js
  src/pages/product/UserProductDetailImg.js
  src/pages/wish/WishList.js
  src/styles/Header.module.css
  src/styles/MainLayout.module.css
  src/styles/PagingBar.module.css
  src/styles/SubHeader.module.css
  src/styles/product/MergeBox.module.css
  src/styles/product/MergeCategory.module.css
  src/styles/product/MergeLayout.module.css
  src/styles/product/ProductCategory.module.css
  src/styles/product/ProductDetailImg.css
  src/styles/product/ProductFilter.module.css
  src/styles/wishList/WishList.module.css
Labels: FEATURE🎉

#74 [FE][FEATURE]상품 수정 진행중
  src/App.js
  src/apis/ProductEditAPICalls.js
  src/pages/product/MyProductList.js
  src/pages/product/ProductEdit.js
  src/pages/product/UsedProductDetail.js
Labels: FEATURE🎉

#78 [FE][BUG]쪽지 리스트 조회 관련
  src/styles/message/MessageList.module.css
Labels: BUG🐛

#79 [FE][FEATURE] 메인 페이지, nav 디자인 어긋난 거 수정
  src/pages/product/Main.js
  src/styles/MainLayout.module.css
  src/styles/SubHeader.module.css
Labels: FEATURE🎉

#80 [FE][FEATURE] 상품수정 진행중
  src/pages/product/ProductEdit.js
Labels: BUG🐛

#82 [FE][FEATURE]상품 수정 진행중
  src/pages/product/ProductEdit.js
Labels: FEATURE🎉

#83 :monocle_face: [FE][REATURE]신고기능 페이징 구현
  src/apis/ReportAPICalls.js
  src/pages/report/ProcessManagement.js
  src/pages/report/ReportSearch.js
  src/pages/report/Search.js
Labels: FEATURE🎉

#85 [FE][Feature] 로그인 추가
  src/apis/UserAPICalls.js
  src/pages/user/Join.js
  src/pages/user/Login.js
Labels: FEATURE🎉, BUG🐛

#90 [FE][BUG]상품수정 완료
  src/apis/ProductEditAPICalls.js
  src/pages/product/AddProduct.js
  src/pages/product/MyProductList.js
  src/pages/product/ProductEdit.js
  src/pages/product/UsedProductDetailInfo.js
Labels: BUG🐛

#89 [FE][FEATURE] 쪽지 (모달)조회 진행중
  src/apis/MessageAPICalls.js
  src/components/message/MessageMenu.js
  src/components/message/Modal.js
  src/components/message/SearchForm.js
  src/pages/message/MessagModal.js
  src/pages/message/MessageDetail.js
  src/pages/message/MessageList.js
  src/pages/product/UsedProductDetailInfo.js
  src/styles/Footer.module.css
  src/styles/Modal.module.css
  src/styles/message/MessageDetail.module.css
  src/styles/message/MessageList.module.css
Labels: FEATURE🎉

#91 :bulb: [FE][FEATURE]신고기능 처리,미처리,검색기능 수정
  src/App.js
  src/apis/ReportAPICalls.js
  src/modules/ReportModule.js
  src/pages/report/ProcessManagement.js
  src/pages/report/Report.js
  src/pages/report/ReportSearch.js
  src/pages/report/Search.js
  src/styles/Header.module.css
  src/styles/Modal.module.css
  src/styles/report/processManagement.module.css
  src/styles/report/reportRegist.module.css
Labels: BUG🐛

#92 [FE][Feature] 회원정보 추가
  public/images/userProfile/origin/test1000-original-lion.jpg
  public/images/userProfile/origin/test500-original-lion.jpg
  public/images/userProfile/origin/test600-original-test1.jpg
  public/images/userProfile/origin/test700-original-lion.jpg
  public/images/userProfile/origin/test800-original-lion.jpg
  public/images/userProfile/origin/test900-original-lion.jpg
  public/images/userProfile/origin/user01-origin-image.jpg
  public/images/userProfile/original/dummy.txt
  public/images/userProfile/thumbnail/dummy.txt
  public/images/userProfile/thumbnail/test1000-thumbnail-lion.jpg
  public/images/userProfile/thumbnail/test500-thumbnail-lion.jpg
  public/images/userProfile/thumbnail/test600-thumbnail-test1.jpg
  public/images/userProfile/thumbnail/test700-thumbnail-lion.jpg
  public/images/userProfile/thumbnail/test800-thumbnail-lion.jpg
  public/images/userProfile/thumbnail/test900-thumbnail-lion.jpg
  public/images/userProfile/thumbnail/user01-thumbnail-image.jpg
  src/App.js
  src/apis/UserAPICalls.js
  src/components/common/Header.js
  src/components/common/SubHeader.js
  src/components/user/WithdrawButton.js
  src/modules/UserModule.js
  src/pages/user/EditMyInfo.js
  src/pages/user/Join.js
  src/pages/user/Login.js
  src/pages/user/MyInfo.js
Labels: FEATURE🎉

#97 [FE][FEATURE]쪽지 모달 완성
  src/apis/MessageAPICalls.js
  src/components/message/Message.js
  src/components/message/MessageMenu.js
  src/pages/message/MessagModal.js
  src/pages/message/MessageList.js
  src/pages/product/UsedProductDetailInfo.js
  src/styles/Modal.module.css
  src/styles/message/MessageList.module.css
Labels: FEATURE🎉

#96 [FE][Feature] 캘린더에 날짜 등록하기
  package-lock.json
  package.json
  src/apis/MyCalendarAPICalls.js
  src/components/MyCalendar/MyCalendarHeader.js
  src/components/MyCalendar/MyCalenderMain.js
  src/components/product/ProductList.js
  src/modules/MyCalendarModule.js
  src/modules/index.js
  src/pages/MyCalendar/MyCalendar.js
  src/pages/product/Merge.js
  src/pages/product/UsedProductDetailInfo.js
  src/styles/myCalendar/MyCalendar.css
Labels: FEATURE🎉

#94 [FE][FEATURE]내판매목록 진행중
  src/apis/ProductEditAPICalls.js
  src/pages/product/AddProduct.js
  src/pages/product/MyProductList.js
  src/pages/product/ProductEdit.js
  src/styles/product/AddProduct.css
Labels: FEATURE🎉

#93 :zap:[BE][FEATURE] 신고처리 완료시 판매자에게 메세지 전송
  src/admin/Management.js
  src/apis/ReportAPICalls.js
  src/modules/ReportModule.js
  src/pages/product/UsedProductDetailInfo.js
  src/pages/report/ProcessDetail.js
  src/pages/report/ProcessManagement.js
  src/pages/report/Report.js
  src/pages/report/ReportUpdate.js
  src/styles/report/Report.module.css
  src/styles/report/reportRegist.module.css
Labels: FEATURE🎉

#99 [FE][Feature] 캘린더로 일정 관리
  package-lock.json
  src/App.js
  src/AuthCheck.js
  src/apis/MyCalendarAPICalls.js
  src/components/MyCalendar/MyCalenderMain.js
  src/components/common/SubHeader.js
  src/components/product/MergeBox.js
  src/modules/MyCalendarModule.js
  src/pages/product/Merge.js
  src/pages/product/UsedProductDetail.js
  src/pages/product/UsedProductDetailInfo.js
  src/styles/Button.module.css
  src/styles/Modal.module.css
  src/styles/myCalendar/MyCalendar.css
  src/styles/myCalendar/MyCalendarAside.css
Labels: FEATURE🎉
